language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: ggxzO7UTxYdG8Snx7PCQALQa663rPgKANkgCF0KSkLmTZbQRnQrMewm8LvlzbLlTOjp1vJ0vrb5GzSvSlO7zobBxvzEfZcmqsbQPu3TkezZxfl59JSMGUPEcDn6xTX8pbrFoDR5Uz+XVL+qFmRRcEu0Z3/yo9suKvRsGhqs41N1Kk39DITqG2vL7rMXT44CRICIGXoGMZJTaWbop6FLk03n6a6jX/arsY69d3pwzJjwVnypp5X//dWo+Xotfbddt83h7qr/33RkXoCvp2eTJZOaYfHxKFHe0ZD6LMrrsy+sAyLE56yfqcbZi9D49hlvpaizKbuta25cphePiXRbfXIKKxiWPjOFJAcVFlxcWI6qQD43v9c4L8NIz8aINOWqfHy0QN8PSwR7bw5qqMmOduI6Dm3sr0PZkmXq2bAwz+LD43MAq0RzYOhqsA/AV5Rl/8THDLTb+5Yq6YoO/JgnbAcPWmvvIcfacl8cCcPDRVD0Xuvz8Ie1aCXKAL93QsII9fVDeG6IuXHsqsdAMfyxacPaF3zq+CmUtIrEUugMLbqu8Ynd/qLiIPanwFuYGGGUsFb4HZbyNwI3KhF4DoEpcZhizQhlAyHbobgzJL6WEuwQO4nO7pp1GsjAlBTYWruxss4k6a9Py1+24HuZJZlaJhMWnEo5cYMzT6VHFnqLOYa8=
  app: thinkful-shopping-list
  on:
    repo: barretthafner/thinkful-shopping-list
notifications:
  email: false
  slack:
    secure: Jwhv/yk/ejof+5xPhBafaJpZ/7QPC0W6M8lgzUAPOB7DpRABB6CEZ1SMwAReSrjbasd8WEoOQ8cqUg55un2pYd2+/0zOKtPNJ/tCyV1W9K9wzl8tpKIhqj+8kwT/VQy18nY7N5PY49c9SK0KDo6LrqBiJ9HWMVbN2xI1y8p8cKaq5dlQHuo2NUtCmt0St8mU8qmFprdbISSWFE+KUcQ+dY8thBrLxFbqDauTMXtB5kHxkIUS88aHP5pqnkmx9GX/JPFupPcy/W5YhEBKqeRFxqcgvDwmB4P2ALA6j2IDMrUDJzCOebjI0Ns37DpROshAp1i2kRMx2pihcnhfFMU8jQYCNapZwomvF/FhVni66Hy+729Q90oFmfMOgIc/bi5CqyUJDs5kgcmmrQvn9M3L6d58eYl8/KNzPcn+uCAvYegkLaJdvIgvXGUzpSIObqO6xMpEnIZaaLOQ0W6pwo+wY2aiW75LJDV9jizNV7a3wrzNr+zYz3VsdRbg+7wqGcyOKzK2kirwCCC91ZLFURmheYFGfOS1BsPzQqRKXFI9J5akzX0CIfBnKbURxdOnTlGcQ2yl54hULzR+xHzFjHoff35pjshAexYprDJTPrsrl9Fxa3G7v/1JXNdHmwT1iZAMF2Vr5+6GaZaOLGhmqeu4Ajl6/+hkyiN28mMRER8+XqE=
